
-define (ALARM_MANAGER, alarm_handler).
%% ====================================================================
%% Alarm definition 
%% purposefully incompleted implementation of 3gpp 328.29-a00,
%% 3gpp alarm Intergration Reference Point
%% ====================================================================

-type alarm_severity() :: critical | major | minor | warning | info.

%% active alarm records
%% fields only describes active alarm
%% historical alarm is not part of this design therefore no clear fields.
%%
-record (alarm, 
                {
                 %% unqiue alarm id, for now it must be generated by the application
                 alarmId :: atom(),

                 %% the time is generated by this module
                 %% erlang system time that might not be align with OS or eNodeB/GPS/NTP time at all.
                 alarmRaisedTime,

                 %% the alarm last seen 
                 alarmChangedTime,

                 %% the alarm cleared time for historical alarm record keeping
                 alarmClearedTime = active,

                 %% more human readable form and non-3GPP standard
                 alarmRaisedUTCTime,
                 alarmChangedUTCTime,
                 alarmClearedUTCTime,
                 
                 %% alarm duplication counter(Non-3GPP)
                 counter = 1 :: integer(),

                 %% describe probably cause
                 probableCause            :: string(),
                 perceivedSeverity = info :: alarm_severity(),
                 specificProblem          :: string(),
                 proposedRepairActions    :: string(),

                 %% modules or components 
                 source :: atom()
        }).
